In [4]:
import pandas as pd
import numpy as np
import random

In [9]:
random.random()

0.8697855491597505

In [11]:
w1 = random.random()
w2 = random.random()
b = random.random()

In [12]:
w1

0.468276992536813

In [15]:
i1 = np.array([1,3,5,6,8,9])
i2 = np.array([2,4,6,5,9,1])
y = np.array([1,0,0,1,0,0])

array([1, 3, 5, 6, 8, 9])

In [21]:
def nn(i1,i2,w1,w2,b):
    s = i1 * w1 + i2 + w2 + b
    return sigmoid(s)
def sigmoid(x):
    sig = (1 / 1 + np.exp(-x))
#     return sig

    if sig >= 0.5:
        return 1
    else: 0

In [66]:
nn(i1,i2,w1,w2,b)

In [30]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

w = np.random.rand(3, 1)
b = np.zeros((1, 1))       

def nn(i):
    s = np.dot(i, w) + b
    out = sigmoid(s)
    return out

# i = np.array([[0.7, 0.3, 0.2]])

d= {"x1": [1,1,0,0],"x2":[1,0,1,0],"y":[1,0,0,0]}
i =  pd.DataFrame(d)

out = nn(i)

print(out)

[[0.75896577]
 [0.60527452]
 [0.53356544]
 [0.5       ]]


In [40]:
import numpy as np
import pandas as pd

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

w = np.random.rand(2, 1)
b = np.zeros((1, 1))       

def nn(inputs):
    s = np.dot(inputs, w) + b
    out = sigmoid(s)
    return out

d = {"x1": [1, 1, 0, 0], "x2": [1, 0, 1, 0], "y": [1, 0, 0, 0]}
df = pd.DataFrame(d)

input_data = df.drop(columns=['y']).values

output = nn(input_data)

output

y1= np.round(output)

In [50]:
y1

array([[1.],
       [1.],
       [1.],
       [0.]])

In [37]:
np.round(output)

array([[1.],
       [1.],
       [1.],
       [0.]])

In [59]:
y1.flatten()

array([1., 1., 1., 0.])

In [61]:
(y1.flatten() - df["y"].values)

array([0., 1., 1., 0.])

In [57]:
df["y"].values
y1

array([[1.],
       [1.],
       [1.],
       [0.]])

In [62]:
c = ((y1.flatten() - df["y"].values) ** 2) / 2

In [63]:
c

array([0. , 0.5, 0.5, 0. ])

In [65]:
import numpy as np
import pandas as pd

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

# Randomly initialize weights and bias
w = np.random.rand(2, 1)
b = np.zeros((1, 1))       

def nn(inputs):
    s = np.dot(inputs, w) + b
    out = sigmoid(s)
    return out

def backpropagation(inputs, targets, learning_rate=0.1, epochs=1000):
    global w, b
    
    for epoch in range(epochs):
        
        predicted_output = nn(inputs)

        error = targets - predicted_output

        output_gradient = sigmoid_derivative(predicted_output)
        delta_output = error * output_gradient

        w += learning_rate * np.dot(inputs.T, delta_output)
        b += learning_rate * np.sum(delta_output, axis=0, keepdims=True)

        if epoch % 100 == 0:
            print(f"Epoch {epoch}, Error: {np.mean(np.abs(error))}")

    return w, b

# Input DataFrame
d = {"x1": [1, 1, 0, 0], "x2": [1, 0, 1, 0], "y": [1, 0, 0, 0]}
df = pd.DataFrame(d)

# Extracting input and target values
input_data = df.drop(columns=['y']).values
targets = df['y'].values.reshape(-1, 1)

# Perform backpropagation
trained_w, trained_b = backpropagation(input_data, targets)

# Print the final weights and bias
print("Trained Weights:")
print(trained_w)
print("\nTrained Bias:")
print(trained_b)

Epoch 0, Error: 0.5047589854527891
Epoch 100, Error: 0.3287833786108268
Epoch 200, Error: 0.2757721908192384
Epoch 300, Error: 0.23983836555668347
Epoch 400, Error: 0.21320207686853496
Epoch 500, Error: 0.19242695913185545
Epoch 600, Error: 0.17562254417380807
Epoch 700, Error: 0.1616634431186732
Epoch 800, Error: 0.14983370199588023
Epoch 900, Error: 0.13965189892765645
Trained Weights:
[[2.99439005]
 [3.00596047]]

Trained Bias:
[[-4.8028046]]
