In [1]:
import numpy as np
import tensorflow as tf

In [6]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

In [7]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [13]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [24]:
model = Sequential()
model.add(Dense(4, input_dim=2, activation='relu'))  
model.add(Dense(1, activation='sigmoid'))  

In [25]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [26]:
model.fit(X, y, epochs=1000)

In [29]:
model.evaluate(X, y)

1/1 [==============================] - 0s 33ms/step - loss: 0.2846 - accuracy: 1.0000


[0.2845783233642578, 1.0]

In [111]:
z = model.predict(X)

1/1 [==============================] - 0s 36ms/step


In [109]:
len(model.predict(X))

1/1 [==============================] - 0s 26ms/step


4

In [113]:
z

array([[0.3019574 ],
       [0.7906861 ],
       [0.72341263],
       [0.19764833]], dtype=float32)

In [114]:
# l= []
# for i in len(model.predict(X)):
#     if i>=0.5:
#         l.append(1)
#     else: l.append(0)

In [31]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [32]:
def sigmoid_derivative(x):
    return x * (1 - x)

In [40]:
i_n = 2
h_n = 3
o_n = 1

In [104]:
def ff(x, w1, w2):

    hidden_input = np.dot(x, w1)
    hidden_output = sigmoid(hidden_input)
    
    output = sigmoid(np.dot(hidden_output, w2))
#     output = (np.dot(hidden_output, w2))
    
    return output

In [105]:
def xor(x1, x2):
    x = np.array([[x1, x2]])
    
    w1 = np.array([[20, 20], [-50, -10]])
    w2 = np.array([[20], [20]])
    
    return ff(x, w1, w2)[0]

In [106]:
xor(1,1),xor(0,1),xor(1,0),xor(0,0)

(array([1.]), array([0.50022699]), array([1.]), array([1.]))

In [64]:
np.random.random()

0.8980718609656692

In [82]:
xor(0, 1)

array([0.5])

In [80]:
xor(0, 0)

array([1.])

In [107]:
input_neurons = 2
hidden_neurons = 4
output_neurons = 1

weights_input_hidden = np.random.uniform(size=(input_neurons, hidden_neurons))


weights_hidden_output = np.random.uniform(size=(hidden_neurons, output_neurons))

epochs = 10000
learning_rate = 0.1

for epoch in range(epochs):

    hidden_layer_input = np.dot(X, weights_input_hidden)
    hidden_layer_output = sigmoid(hidden_layer_input)

    output_layer_input = np.dot(hidden_layer_output, weights_hidden_output)
    output = sigmoid(output_layer_input)

    error = y - output

    slope_output_layer = sigmoid_derivative(output)
    delta_output = error * slope_output_layer

    error_hidden_layer = delta_output.dot(weights_hidden_output.T)
    slope_hidden_layer = sigmoid_derivative(hidden_layer_output)
    delta_hidden = error_hidden_layer * slope_hidden_layer

    weights_hidden_output += hidden_layer_output.T.dot(delta_output) * learning_rate
    weights_input_hidden += X.T.dot(delta_hidden) * learning_rate

hidden_layer_input = np.dot(X, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_input = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_input)

print("Predicted Output:")
print(output)

Predicted Output:
[[0.09677031]
 [0.92172181]
 [0.92398464]
 [0.06415507]]
