In [2]:
!pip install numba

In [3]:
import numpy as np
from numba import njit, prange
import time

In [7]:
N = 3

In [8]:
@njit(parallel=True)
def multiply_matrix(A, B, result):
    for i in prange(N):
        for j in range(N):
            result[i, j] = 0
            for k in range(N):
                result[i, j] += A[i, k] * B[k, j]

In [9]:
if __name__ == "__main__":
    A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
    result = np.zeros((N, N))

    # Perform matrix multiplication
    start_time = time.time()
    multiply_matrix(A, B, result)
    end_time = time.time()

    # Display matrices and result
    print("Matrix A:")
    print(A)
    print("\nMatrix B:")
    print(B)
    print("\nResult Matrix:")
    print(result)

    # Display execution time
    print("\nMatrix multiplication took", end_time - start_time, "seconds.")

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Result Matrix:
[[ 30.  24.  18.]
 [ 84.  69.  54.]
 [138. 114.  90.]]

Matrix multiplication took 0.3213155269622803 seconds.
